pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label="MERGE WITH MERGIFY"
      - label!="DONT MERGE"
      - label!="bp-conflict"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: merge
        
  - name: automatic squash and merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label="SQUASH & MERGE WITH MERGIFY"
      - label!="DONT MERGE"
      - label!="bp-conflict"
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge
