git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  matrix:
    - CONFIG=DefaultConfig                  CHISEL_VERSION=3
    - CONFIG=DefaultL2Config                CHISEL_VERSION=3
    - CONFIG=RoccExampleConfig              CHISEL_VERSION=3
    - CONFIG=DualCoreConfig                 CHISEL_VERSION=3
    - CONFIG=MemtestConfig                  CHISEL_VERSION=3
    - CONFIG=FancyMemtestConfig             CHISEL_VERSION=3
    - CONFIG=BroadcastRegressionTestConfig  CHISEL_VERSION=3
    - CONFIG=CacheRegressionTestConfig      CHISEL_VERSION=3
    - CONFIG=NastiConverterTestConfig       CHISEL_VERSION=3
    - CONFIG=UnitTestConfig                 CHISEL_VERSION=3
    - CONFIG=SplitL2MetadataTestConfig      CHISEL_VERSION=3

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - hurricane

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

script:
  - make vsim-verilog -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=$CHISEL_VERSION
  - make fsim-verilog -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=$CHISEL_VERSION
  - make emulator-ndebug -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=$CHISEL_VERSION
  - make emulator-asm-tests   -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=$CHISEL_VERSION
  - make emulator-bmark-tests -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=$CHISEL_VERSION -j1

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
